# Top-level Makefile for ITRANSNET

SUBDIRS = XML

ROOT = ../../..

#DefaultSensor.class: Sensor.class DefaultSensor.java
	
#DummySensor.class: Sensor.class DummySensor.java
#all: Sensor.class DefaultSensor.class Car.class Road.class Map.class

#Sensor.class: Sensor.java
#	$(JAVAC) $<
#DefaultSensor.class: Sensor.class DefaultSensor.java
#	$(JAVAC) DefaultSensor.java
#DummySensor.class: Sensor.class DummySensor.java
#	$(JAVAC) DummySensor.java
include $(ROOT)/Makefile.include

