#COMPONENT=ArrayListTestC
#COMPONENT=EventMetaTestC
COMPONENT=EventMetaMsgTestC
#COMPONENT=EventInstanceTestC
#COMPONENT=EventRoutingTestC
#COMPONENT=PSWareTestC
CFLAGS=-I../../tos/lib/VM/opcodes -I../../tos/lib/VM/contexts -I../../tos/lib/VM/languages  -I../../tos/lib/VM/components -I../../tos/lib/VM/types -I../../tos/lib/VM/interfaces -I%T/lib/Queue -I../../tos/lib/ArrayList -I../PSWare -I../rsu_relay -I$(TOSROOT)/tos/sensorboards/micasb
PFLAGS=-v
MSG_SIZE=29

include $(TOSROOT)/apps/Makerules
