COMPONENT=ITS
#COMPONENT=Test
#SENSORBOARD=basicsb
SENSORBOARD=micasb

PFLAGS= -I%T/lib/Queue -I%T/lib/Broadcast -I%T/lib/Route -DDELUGE_GENERIC_COMM_PROMISCUOUS -DDELUGE_ENABLED -v #-DMULTIHOP #-DPLATFORM_PC -I%T/lib/Deluge -I%T/lib/Flash -I%T/lib/Flash/STM25P #

include $(TOSROOT)/apps/Makerules
